### ISSUE TITLE
Error loading module 'Elixir.Hex'

### ISSUE THREAD

**Issue by asntc** [dwyl/phoenix-liveview-calculator#5]
just tried to run: `mix deps.get`

got:
```sh
18:29:22.367 [error] beam/beam_load.c(210): Error loading module 'Elixir.Hex':
  This BEAM file was compiled for an old version of the runtime system.
  To fix this, please re-compile this module with Erlang/OTP 24 or later.

18:29:22.384 [error] beam/beam_load.c(210): Error loading module 'Elixir.Hex':
  This BEAM file was compiled for an old version of the runtime system.
  To fix this, please re-compile this module with Erlang/OTP 24 or later.



* creating /Users/n/.mix/archives/hex-2.1.1
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (UndefinedFunctionError) function Hex.start/0 is undefined (module Hex is not available). Did you mean:

      * Mix.Hex.start/0

    Hex.start()
    (mix 1.17.3) lib/mix/hex.ex:60: Mix.Hex.start/0
    (mix 1.17.3) lib/mix/dep/loader.ex:189: Mix.Dep.Loader.with_scm_and_app/5
    (mix 1.17.3) lib/mix/dep/loader.ex:141: Mix.Dep.Loader.to_dep/4
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (mix 1.17.3) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/3
    (mix 1.17.3) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/1
    (mix 1.17.3) lib/mix/dep/converger.ex:97: Mix.Dep.Converger.all/4
```

**Comment by asntc** [comment]
running `mix local.hex` solved the issue.
I had the latest `Elixir`, but somehow had outdated deps cached. 
all good now.
